// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactBootstrap from "react-bootstrap";

function App(Props) {
  return React.createElement(ReactBootstrap.Container, {
              fluid: true,
              children: React.createElement(ReactBootstrap.Row, {
                    noGutters: true,
                    children: React.createElement(ReactBootstrap.Col, {
                          lg: {
                            offset: 3
                          },
                          sm: 6,
                          children: "obj"
                        })
                  })
            });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
