// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Client from "@apollo/client";
import * as ReactBootstrap from "react-bootstrap";

var client = new Client.ApolloClient({
      uri: "/graphql"
    });

console.log(client);

function App(Props) {
  return React.createElement(ReactBootstrap.Container, {
              fluid: true,
              children: React.createElement(ReactBootstrap.Row, {
                    children: React.createElement(ReactBootstrap.Col, {
                          lg: {
                            offset: 2
                          },
                          children: null
                        }, React.createElement("h1", undefined, "Hello!!!"), React.createElement("p", undefined, "obj"), React.createElement(Client.ApolloProvider, {
                              client: client,
                              children: React.createElement("p", undefined, "obj2")
                            }))
                  })
            });
}

var make = App;

export {
  client ,
  make ,
  
}
/* client Not a pure module */
